[package]
name = "db"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "ahnlich-db"
path = "src/main.rs"

# WARN!!! - used for rust client test, benchmarking and not to be released
[lib]
name = "ahnlich_db"
path = "src/lib.rs"
bench = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flurry.workspace = true
serde.workspace = true
blake3.workspace = true
ndarray.workspace = true
bincode.workspace = true
itertools.workspace = true
clap.workspace = true
thiserror.workspace = true
utils = { path = "../utils", version = "*" }
ahnlich_types = { path = "../types", version = "*" }
tokio.workspace = true
tokio-graceful.workspace = true
cap = "0.1.2"
once_cell.workspace = true
tracing.workspace = true
tracer = { path = "../tracer", version = "*" }
serde_json.workspace = true


[dev-dependencies]
futures.workspace = true
once_cell.workspace = true
pretty_assertions.workspace = true
criterion = "0.4"
rand = "0.8"

[[bench]]
name = "database"
harness = false
