name: Ahnlich Test PRs for Performance Regression

on:
  pull_request:
    branches: ["main"]
    paths:
      - ahnlich/**

env:
  CARGO_TERM_COLOR: always

permissions:
  contents: read
  pull-requests: write

jobs:
  run-benchmark-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        # Ensure we fetch enough history to compare branches
        fetch-depth: 2
        ref: main

    - name: Set up Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: ahnlich

    - name: Install Cargo critcmp
      working-directory: ./ahnlich
      run: cargo install critcmp

    - name: Run benchmarks on main branch
      working-directory: ./ahnlich
      run: cargo bench --bench database -- --save-baseline main

    - name: Checkout PR branch
      uses: actions/checkout@v4
      with:
        # This ensures that we get the correct branch from the forked repo
        ref: ${{ github.event.pull_request.head.ref }}
        repository: ${{ github.event.pull_request.head.repo.full_name }}
        clean: false

    - name: Run benchmarks on PR branch
      working-directory: ./ahnlich
      run: cargo bench --bench database -- --save-baseline pr

    - name: Compare benchmarks
      working-directory: ./ahnlich
      run: |
        benchmark_output=$(critcmp main pr)
        echo $benchmark_output
        echo "## Benchmark Results" >> bench_results.md
        echo "\`\`\`" >> bench_results.md
        echo "$benchmark_output" >> bench_results.md
        echo "\`\`\`" >> bench_results.md

    - name: Comment PR with benchmark results
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: ahnlich/bench_results.md
        comment_tag: benchmark
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Ensure the token is passed correctly