name: Ahnlich Test PRs for Performance Regression

on:
  pull_request:
    branches: ["main"]
    paths:
      - ahnlich/**

env:
  CARGO_TERM_COLOR: always

jobs:
  run-benchmark-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - name: Set up Rust cache
      uses: Swatinem/rust-cache@v2
      with:
        workspaces: ahnlich


    - name: Install Cargo benchcmp
      working-directory: ./ahnlich
      run: cargo install cargo-benchcmp

    - name: Run benchmarks on PR branch
      working-directory: ./ahnlich
      run: cargo bench -- --output-format bencher > pr_bench.txt

    - name: Checkout main branch
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Run benchmarks on main branch
      working-directory: ./ahnlich
      run: cargo bench -- --output-format bencher > main_bench.txt

    - name: Compare benchmarks
      working-directory: ./ahnlich
      run: |
        benchmark_output=$(cargo benchcmp main_bench.txt pr_bench.txt)
        echo "## Benchmark Results" >> bench_results.md
        echo "\`\`\`" >> bench_results.md
        echo "$benchmark_output" >> bench_results.md
        echo "\`\`\`" >> bench_results.md

    - name: Comment PR with execution number
      uses: thollander/actions-comment-pull-request@v2
      with:
        filePath: ahnlich/bench_results.md
        comment_tag: benchmark
