name: Publish Test Results

on:
  workflow_run:
    workflows: [Ahnlich TestSuite]
    types:
      - completed
permissions:
      checks: write
      pull-requests: write
      contents: read
      issues: read
      actions: read

jobs:
  download-and-publish-test-results:
    name: Download and Publish Test Results
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion != 'skipped'
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: Download and Extract Artifacts
        uses: dawidd6/action-download-artifact@e7466d1a7587ed14867642c2ca74b5bcc1e19a2d
        with:
            run_id: ${{ github.event.workflow_run.id }}
            path: artifacts

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        with:
          commit: ${{ github.event.workflow_run.head_sha }}
          files: artifacts/**/*.xml